### ISSUE TITLE
You might interested in sphinxnotes-lilypond

### ISSUE THREAD

**Issue by SilverRainZ** [jianpu-ly/jianpu-st#1]
Hello @suntong, I found that you are using Lilypond and jianpu-ly to write music scores. I wrote a [Sphinx extension](https://sphinx.silverrainz.me/lilypond/) that can help people insert scores into Sphinx documentation, so Lilypond source code (or Jianpu source) can be automatically converted to image and audio and then shown on the documentation. I think you might interested in it.

![图片](https://github.com/jianpu-ly/jianpu-st/assets/8090459/6a7a5a8d-12ab-41c5-bd34-bab42033b128)

**Comment by suntong** [comment]
Yes @ssb22 told me about it before.  
It's a good one but I personally am not using the Sphinx Notes.   
Good to know, will keep a reference and am closing this now.
